### ISSUE TITLE
"Cannot start process because a file name has not been provided"

### ISSUE THREAD

**Issue by michaeldickens** [treellama/weland#30]
I created a simple map with a few polygons as a sort of "Hello World" test. When I tried to switch to visual view, Weland raised an Unhandled Exception:

    Cannot start process because a file name has not been provided.
    
    at System.Diagnostics.Process.Start()
    at Weland.MapWindow.VisualMode()
    at Weland.MapWindow.OnViewMenu(Object obj, EventArgs args)

Then when I close the exception dialog box, Weland quits.

"A file name has not been provided" seems to imply that I need to name and save the map file for visual mode to work, but I did that and I still get the error.

In case it's helpful, I attached the map file that I was using (I renamed it from Map.sceA to Map.sceA.txt because GitHub won't let me upload .sceA files).

[Map.sceA.txt](https://github.com/user-attachments/files/15991032/Map.sceA.txt)

**Comment by michaeldickens** [comment]
Never mind I figured it out, Weland doesn't have a visual mode, you have to edit using Aleph One.
